name: Windows C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Set Windows SDK environment variables
      run: |
        $sdkPath = "C:\Program Files (x86)\Windows Kits\10"
        $includePath = "$sdkPath\Include\10.0.19041.0\ucrt;$sdkPath\Include\10.0.19041.0\shared;$sdkPath\Include\10.0.19041.0\um;$sdkPath\Include\10.0.19041.0\winrt"
        $libPath = "$sdkPath\Lib\10.0.19041.0\ucrt\x64;$sdkPath\Lib\10.0.19041.0\um\x64"
        echo "INCLUDE=$includePath" | Out-File -Append $env:GITHUB_ENV
        echo "LIB=$libPath" | Out-File -Append $env:GITHUB_ENV
      shell: pwsh
    - name: List files for debug
      run: dir
    - name: Build with PowerShell script
      run: pwsh -File build-controller.ps1
    - name: Upload test executable
      uses: actions/upload-artifact@v4
      with:
        name: test_controller
        path: Controller\test_controller.exe

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Download test executable
      uses: actions/download-artifact@v4
      with:
        name: test_controller
        path: .\Controller
    - name: Run unit tests
      run: |
        .\Controller\test_controller.exe
