name: Windows C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: List files for debug
      run: dir
    - name: Build with PowerShell script
      run: pwsh -File build-controller.ps1
    - name: List files for debug
      run: dir
    - name: Upload test executable
      uses: actions/upload-artifact@v4
      with:
        name: test_controller
        path: test_controller.exe
    - name: Upload main executable
      uses: actions/upload-artifact@v4
      with:
        name: main_exe
        path: main.exe

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Download test executable
      uses: actions/download-artifact@v4
      with:
        name: test_controller
        path: .\Controller
    - name: Download main executable
      uses: actions/download-artifact@v4
      with:
        name: main_exe
        path: .\Controller
    - name: Run unit tests
      run: |
        .\Controller\test_controller.exe
    - name: Start main.exe
      run: |
        Start-Process -FilePath ".\Controller\main.exe"
        Start-Sleep -Seconds 2
    - name: Run integration tests
      run: |
        .\Controller\test_controller.exe
